"""Shared fixtures.

The price series here is generated by a small linear congruential generator
rather than by numpy, so it is byte-for-byte reproducible across numpy versions.
The regression baselines depend on it, so changing this generator invalidates
them and they must be regenerated (see `testing/generate_baseline.py`).
"""

import pandas as pd
import pytest

BARS = 400
SEED = 12345


def _uniforms(count: int, seed: int = SEED) -> list[float]:
    """Deterministic uniforms in [0, 1). Not for anything but test fixtures."""
    modulus = 2**31
    state = seed
    out = []
    for _ in range(count):
        state = (1103515245 * state + 12345) % modulus
        out.append(state / modulus)
    return out


def synthetic_ohlcv(bars: int = BARS, seed: int = SEED) -> pd.DataFrame:
    """A deterministic OHLCV frame with mild upward drift and realistic bars."""
    u = _uniforms(bars * 3, seed)
    closes = [100.0]
    for i in range(bars - 1):
        step = (u[i] - 0.5) * 0.02 + 0.0004
        closes.append(closes[-1] * (1 + step))

    rows = []
    for i, close in enumerate(closes):
        open_ = closes[i - 1] if i else close
        hi_pad = 1 + u[bars + i] * 0.008
        lo_pad = 1 - u[bars * 2 + i] * 0.008
        high = max(open_, close) * hi_pad
        low = min(open_, close) * lo_pad
        rows.append(
            {
                "Open": round(open_, 4),
                "High": round(high, 4),
                "Low": round(low, 4),
                "Close": round(close, 4),
                "Volume": 1_000_000 + int(u[i] * 500_000),
            }
        )

    return pd.DataFrame(rows, index=pd.date_range("2024-01-01", periods=bars, freq="B"))


@pytest.fixture(scope="session")
def ohlcv() -> pd.DataFrame:
    return synthetic_ohlcv()
